name: fifteen-puzzle-gpu
channels:
  - pytorch
dependencies:
  - python=3.6
  - numpy
  - scipy
  - pytest
  - tensorflow-gpu
  - keras
  - cudatoolkit=9.0
  - scikit-learn
  - pandas
  - matplotlib
  - jupyter
  - cython
