name: fifteen-puzzle
channels:
  - pytorch
dependencies:
  - python=3.6
  - numpy
  - scipy
  - tensorflow
  - keras
  - pytorch-cpu
  - torchvision-cpu
  - pytorch
  - scikit-learn
  - pandas
  - matplotlib
  - jupyter
  - cython
